version: '3.4'
services:
  my-all-in-one-share:
    image: alfresco-share-my-all-in-one:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../my-all-in-one-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8888"
      REPO_HOST: my-all-in-one-acs
      REPO_PORT: 8080
      ACTIVEMQ_HOST: my-activemq
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  my-all-in-one-acs:
    image: alfresco-content-services-my-all-in-one:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../my-all-in-one-platform-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - my-all-in-one-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - my-all-in-one-postgres
  my-all-in-one-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    ports:
      - "${postgres.port}:5432"
    volumes:
      - my-all-in-one-db-volume:/var/lib/postgresql/data
  my-all-in-one-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: my-all-in-one-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: my-all-in-one-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - my-all-in-one-ass-volume:/opt/alfresco-search-services/contentstore
      - my-all-in-one-ass-volume:/opt/alfresco-search-services/data
  my-activemq:
    image: webcenter/activemq
    environment:
      ACTIVEMQ_CONFIG_MINMEMORY: 512
      ACTIVEMQ_CONFIG_MAXMEMORY: 1024
    ports:
      - "61616:61616"
volumes:
  my-all-in-one-acs-volume:
    external: true
  my-all-in-one-db-volume:
    external: true
  my-all-in-one-ass-volume:
    external: true