pipeline {
    agent any
    stages {
        stage('Build and Test') {
            steps {
                sh './run.sh build_test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
